version: '3.8'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8989:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=sompartyMsk
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=b-1.msk-cluster.kafka.ap-northeast-2.amazonaws.com:9092,b-2.msk-cluster.kafka.ap-northeast-2.amazonaws.com:9092,b-3.msk-cluster.kafka.ap-northeast-2.amazonaws.com:9092
      - KAFKA_CLUSTERS_0_SECURITY=PLAINTEXT
      - KAFKA_CLUSTERS_0_SECURITY=SASL_SSL
      - KAFKA_CLUSTERS_0_SASL_MECHANISM=AWS_MSK_IAM
      - KAFKA_CLUSTERS_0_PROPERTIES_AUTHENTICATION=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler