spring:
  datasource:
    url: ${DB_URL}
    #    url: jdbc:mysql://localhost:3306/acc
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  cloud:
    aws:
      region: ${AWS_REGION}
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        queue-name: ${AWS_SQS_QUEUE_NAME}
    stack:
      auto: false