spring:
  datasource:
    url: jdbc:mysql://localhost:3306/acc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  data:
    redis:
      #      host: ${elastiCache_endPoint}
      host: 127.0.0.1
      port: 6379
      repositories:
        enabled: false
  cloud:
    aws:
      queue:
        region: ${QUEUE_REGION}
        access-key: ${QUEUE_ACCESS_KEY}
        secret-key: ${QUEUE_SECRET_KEY}
      sqs:
        queue-name: ${SQS_QUEUE_NAME}
    stack:
      auto: false