spring:
  datasource:
    url: ${rds.url}
    username: ${rds.user}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  aws:
    dynamodb:
      endpoint: ${dynamodb.url}
      region: ${region}
  data:
    redis:
      host: ${elastic_cache.url}
      port: 6379
  cloud:
    aws:
      region:
        static: ${region}
        credentials:
          instance-profile: true # IAM 역할 사용
        stack:
          auto: false
      queue:
        region: ${region}
      sqs:
        queue-name: ${wait_sqs.name}
aws:
  noti:
    region: ${region}
    sqs:
      queue-name: ${noti_sqs.name}
      queue-url: ${noti_sqs.url}
    sns:
      application-arn: ${noti_sns.arn}

  auth:
    cognito:
      user-pool-id: ${cognito.user_pool_id}
      app-client-id: ${cognito.client_id}
      client-secret: ${cognito.client_secret}
      jwks-url: ${cognito.jwks_url}
logging:
  level:
    root: INFO
    org.apache.kafka: ERROR